version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: 'on'
          GOPROXY: https://proxy.golang.org
    steps:
      - checkout
      - run: (cd golang/gogo && go test -v ./...)
      - run: (cd golang/protobuf && go test -v ./...)

workflows:
  version: 2
  test:
    jobs:
      - test
