version: 2

jobs:
  test:
    working_directory: ~/go/src/github.com/lightstep/lightstep-tracer-common
    docker:
      - image: circleci/golang:1.10
    steps:
      - run:
          name: "configure environment"
          command: |
            echo 'export GOPATH="$HOME/go"' >> $BASH_ENV
            source $BASH_ENV
      - checkout
      - run: make test

workflows:
  version: 2
  test:
    jobs:
      - test
