version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: 'on'
          GOPROXY: https://proxy.golang.org
    steps:
      - checkout
      - run: go test -v ./golang

workflows:
  version: 2
  test:
    jobs:
      - test
